// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlYQ6ybbFIj8e3dut4WSskopNxaP8gYQs',
    appId: '1:610054981518:web:872ba754387d77005486df',
    messagingSenderId: '610054981518',
    projectId: 'my-flutterfire-7365a',
    authDomain: 'my-flutterfire-7365a.firebaseapp.com',
    storageBucket: 'my-flutterfire-7365a.appspot.com',
    measurementId: 'G-K4YL1EX23P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxUJLYyVgUB4SAEUPMfcLtTB0mA8jfISM',
    appId: '1:610054981518:android:266a6d70c67664535486df',
    messagingSenderId: '610054981518',
    projectId: 'my-flutterfire-7365a',
    storageBucket: 'my-flutterfire-7365a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTk2gBgcu4Is_ovVz2cTf23Zi86nddPBw',
    appId: '1:610054981518:ios:efd1c7a84a91b8ff5486df',
    messagingSenderId: '610054981518',
    projectId: 'my-flutterfire-7365a',
    storageBucket: 'my-flutterfire-7365a.appspot.com',
    iosClientId: '610054981518-3n39f0hnd1iqke632luhnqrie4dv2csv.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTk2gBgcu4Is_ovVz2cTf23Zi86nddPBw',
    appId: '1:610054981518:ios:efd1c7a84a91b8ff5486df',
    messagingSenderId: '610054981518',
    projectId: 'my-flutterfire-7365a',
    storageBucket: 'my-flutterfire-7365a.appspot.com',
    iosClientId: '610054981518-3n39f0hnd1iqke632luhnqrie4dv2csv.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterfire',
  );
}
